# Generated by Django 4.2.2 on 2023-08-01 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements81', '0002_advertisements81_bu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisements81',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='advertisements81',
            name='updated_time',
        ),
        migrations.AlterModelTable(
            name='advertisements81',
            table='advertisements',
        ),
    ]
