# Generated by Django 4.2.2 on 2023-08-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0002_advertisements81_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisements81',
            name='image',
            field=models.ImageField(default='', upload_to='advertisements/', verbose_name='изображение'),
            preserve_default=False,
        ),
    ]
