# Generated by Django 4.2.2 on 2023-08-23 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0003_advertisements81_image'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisements81',
            table='advertisements1',
        ),
    ]
