# Generated by Django 4.2.2 on 2023-08-23 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0005_alter_advertisements81_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisements81',
            table='advertisements1',
        ),
    ]
